# Generated by Django 2.1 on 2019-11-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.TextField(max_length=200)),
                ('image_des', models.TextField(max_length=500)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
