# Generated by Django 2.1 on 2019-11-15 04:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexmodel',
            old_name='index_image',
            new_name='index_image1',
        ),
        migrations.AddField(
            model_name='indexmodel',
            name='index_image2',
            field=models.FileField(default=datetime.datetime(2019, 11, 15, 4, 46, 37, 107556, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexmodel',
            name='index_image3',
            field=models.FileField(default=datetime.datetime(2019, 11, 15, 4, 46, 47, 426528, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
