# Generated by Django 2.1 on 2019-11-15 05:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20191115_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexmodel',
            old_name='twitterlink',
            new_name='gmaillink',
        ),
        migrations.AddField(
            model_name='indexmodel',
            name='pinterestlink',
            field=models.TextField(default=datetime.datetime(2019, 11, 15, 5, 30, 48, 609554, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
