# Generated by Django 2.1 on 2019-12-15 07:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20191215_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='address',
        ),
        migrations.AddField(
            model_name='information',
            name='addressline1',
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='addressline2',
            field=models.TextField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='addressline3',
            field=models.TextField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='time',
            field=models.TextField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='information',
            name='phone',
            field=models.TextField(max_length=50),
        ),
    ]
